### ISSUE TITLE
License

### ISSUE THREAD

**Issue by 2br-2b** [farirat/autoshard-scaler#1]
Hello!

I'm looking to autoscale my discord.py bot on kubernetes, and this looks close to what I need!

Have you considered adding a license to this code? That way, people like me don't have to worry about using copyrighted code!

I'd prefer it if the license didn't require source code to be public (my bot isn't open source), but I understand either way.

Thank you!

**Comment by farirat** [comment]
Hello !

I'll add an Apache2 license.

Thank you !
